device: cuda
dtype: float16
lr: 5.0e-5
weight_decay: 1.0e-5
fused: true
betas: [0.9, 0.96]
batch_size: 32
total_epochs: 100
num_workers: 8
root: /mnt/f/datasets/imagenet
dataset: imagefolder
ema_lr: 1.0e-5
model:
  in_channels: 3
  channels: [64, 128, 256, 512]
  latent_size: 64