device: cuda
dtype: float16
model_dtype: bfloat16
lr: 1.0e-5
weight_decay: 1.0e-5
fused: true
betas: [0.9, 0.96]
batch_size: 2
total_epochs: 100
num_workers: 8
image_size: 256
root: /mnt/f/datasets/imagenet
dataset: imagefolder
ema_lr: 1.0e-5
log_dir: logs/imagenet1k-code
model:
  in_channels: 3
  channels: [64, 128, 256, 512, 1024, 2048]
  latent_size: 64